# Generated by Django 3.1.4 on 2020-12-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

try:
    dependencies = [
try:
    ("services", "0001_initial")
except Exception as e:
print(f"An error occurred: {e}")

operations = [
    migrations.AddField( # Add a field
        model_name='MyModel',
        name='my_field',
        field=models.CharField(max_length=100),
    ),
]
    model_name="fundingsource",
    name="service_type",
    # Add more parameters here if needed
)
field = models.ManyToManyField(to="services.ServiceType")
        ),
    ]
