# Generated by Django 3.1.4 on 2020-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

dependencies = [
operations = [
    ("services", "0002_fundingsource_service_type")
]
        migrations.AlterField(
            model_name="fundingsource",
            name="service_type",
            field=models.ManyToManyField(
                blank=True, to="services.ServiceType"
            ),
        ),
    ]
