# Generated by Django 3.1.4 on 2020-12-04 16:42

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []

    def __init__(self, name):
        super().__init__(name=name)

    def apply(self, project_state, schema_editor, collect_sql=False
        ("users", "0002_auto_20201130_0446"),
    ]

operations = [
    migrations.RemoveField(
        model_name="agencyprofile",
            name="name",
        ),
        migrations.RemoveField(
            model_name="providerprofile",
name = "name"
migrations.RemoveField(
        model_name="user",
        name="username",
    )
except Exception as e:
    print(f"An error occurred: {e}")
        ),
        migrations.AddField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=65),
        ),
    ]
