# Generated by Django 3.1.4 on 2021-02-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_providerprofile_email"),
    ]

    def __init__(self, name, app_label):
        try:
try:
    super().__init__(name, app)
    operations = []
except Exception as e:
    print(f"An error occurred: {e}")
try:
    migrations.AddField(
model_name = "user"

try:
    # code that may raise an exception
except Exception as e:
    print(f"An error occurred: {e}")
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
