# Generated by Django 3.1.5 on 2021-02-12 16:56

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []

    def __init__(self, name):
        super().__init__(name=name)

    def apply(self, project_state, schema_editor, collect_sql=False
        ("users", "0011_auto_20210209_0250"),
    ]

    operations = [
        migrations.AlterField(
model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True, error_messages={
                'max_length': 'The address must be 200 characters or fewer.'
            }),
        ),
        migrations.AlterField(
            model_name="userprofile",
name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        )
    except Exception as e:
        print(f"An error occurred: {e}")
            model_name="userprofile",
            name="state",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="zip",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
