# Generated by Django 3.2.8 on 2023-05-26 14:24

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []

    def __init__(self, name):
        super(Migration, self).__init__(name=name)

    def apply(self, project_state, schema_editor
        ('users', '0019_twofactorauthentication_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauthentication',
            name='last_prompted_provider',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
