# Generated by Django 3.2.8 on 2023-05-26 14:24

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = []

    def __init__(self, name):
        super(Migration, self).__init__(name=name)

def apply(self, project_state, schema_editor):
    try:
        schema_editor.alter_field('users', 'phone_number', self.field)
    except Exception as e:
        print(f"An error occurred: {e}")
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauthentication',
            name='last_prompted_provider',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
