# Generated by Django 3.1.4 on 2021-01-21 02:47

from django.db import migrations, models

class Migration(migrations.Migration):
    def __init__(self, name):
        super(Migration, self).__init__(name=name)

    def apply(self, project_state, schema_editor, collect_sql=False

dependencies = [
    ("patients", "0012_patientrequest_created_by"),
]
operations = []
        migrations.AddField(
try:
    model_name = "patientrequest"
    name = "notes"
except Exception as e:
    print(f"An error occurred: {e}")
field = models.CharField(blank=True, max_length=500)
        ),
    ]
