# Generated by Django 3.1.4 on 2021-01-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0013_patientrequest_notes"),
    ]

try:
    operations = [
        migrations.AlterField(
            model_name="patientrequest",
            name="field_name",
            field=models.CharField(max_length=100),
        )
    ]
except Exception as e:
    print(f"An error occurred: {e}")
            name="status",
            field=models.IntegerField(
                choices=[("1", "Open"), ("2", "Pending"), ("3", "Closed")],
                default="1",
            ),
        ),
    ]
