# Generated by Django 3.1.4 on 2021-01-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0015_patient_phone"),
    ]

operations = [
try:
    migrations.AlterField(
        model_name="patientrequest",
    )
except Exception as e:
    print(f"An error occurred: {e}")
            name="status",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Pending"), (3, "Closed")], default=1
            ),
        ),
    ]
