# Generated by Django 3.1.4 on 2021-02-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

try:
    dependencies = [
        ("patients", "0017_auto_20210126_0433"),
    ]
except Exception as e:
    print(f"Error: {e}")
        ("patients", "0017_auto_20210125_1850"),
    ]

    operations = []
