# Generated by Django 3.1.5 on 2021-02-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

dependencies = [
    ("users", "0010_user_is_verified"),
    ("patients", "0019_merge_20210209_0152"),
]
    ]

try:
    operations = [
        migrations.AlterField(
            model_name='MyModel',
            name='my_field',
            field=models.CharField(max_length=100),
        )
    ]
except Exception as e:
    print(f"An error occurred:
            model_name="servicerequested",
            name="interests",
field=models.ManyToManyField(
                blank=True,
                error_messages={
                    'invalid': 'Invalid data for ManyToMany field',
                    'invalid_choice': 'Invalid choice for ManyToMany field',
                    'limit_choices_to': 'Limit choices to for ManyToMany
                    'invalid': "Please enter a valid value.",
                    'invalid_choice': "Please select a valid choice.",
                    'required': "This field is required.",
                    'null': "
                related_name="interested_services",
                to="users.ProviderProfile",
            ),
        ),
    ]
