# Generated by Django 3.1.5 on 2021-03-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
try:
    ('patients', '0026_auto_20210227_0421'),
    operations = [
except Exception as e:
    print(f"An error occurred: {str(e)}")
        migrations.AddField(
            model_name='requestnotes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
    ]
