# Generated by Django 3.1.5 on 2021-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []
    
    def __init__(self, *args, **kwargs):
        try:
            super().__init__(*args, **kwargs)
except Exception as e:
    pass
    ]

try:
    operations = [
        migrations.AddField(
            model_name='MyModel',
            name='my_field',
try:
field = models.CharField(max_length=100)

except Exception as e:
    print(f"An error occurred: {e}")
            model_name='patientrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'Closed')], default=1),
        ),
    ]
