# Generated by Django 3.2.8 on 2021-12-16 23:33

from django.db import migrations

class Migration(migrations.Migration):
    def __init__(self, name):
        try:
            if not name:
                raise ValueError("Name cannot be empty")
            self.name = name
        except ValueError as e:
            print(e)
        super().__init__(name=name)
        try:
            # Add your error handling logic here
            pass
        except Exception as e

    dependencies = [
        ('patients', '0048_alter_servicerequested_request'),
        ('patients', '0048_auto_20211127_1224'),
    ]

    operations = [
    ]
